package com.richardsenger.piratesnships.combat.grapple;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.charset.StandardCharsets;

/**
 * The placeholder {@code item/musket_hook} model (GR3): a copy of the hand-made {@code musket_loaded} model with a small
 * iron hook sticking out of the muzzle (a shank along the barrel, a crown and two flukes bent back), shown through the
 * musket's {@code pirates_n_ships:grapple_loaded} override. Built by datagen from the hand-made file so the two stay in
 * step; a Blockbench {@code musket_hook} replaces it in an art batch. Pure Gson, tested in JUnit.
 */
public final class MusketHookModel {

    /** Classpath location of the model this one copies. */
    public static final String BASE = "/assets/pirates_n_ships/models/item/musket_loaded.json";

    /** Muzzle tip of the musket models (top centre of the barrel turned −45° about z, in model pixels). */
    static final double MUZZLE_X = 16.57;
    static final double MUZZLE_Y = 17.58;
    static final double MUZZLE_Z = 8.0;
    /** The barrel lies turned −45° about z, like every element of the musket. */
    static final float BARREL_ANGLE = -45f;

    /** Names of the added elements. */
    static final String[] HOOK_ELEMENTS = {"hook_shank", "hook_crown", "hook_fluke_left", "hook_fluke_right"};

    private MusketHookModel() {
    }

    /** Reads the base model from the classpath and adds the hook. */
    public static JsonObject build() {
        try (InputStream in = MusketHookModel.class.getResourceAsStream(BASE)) {
            if (in == null) {
                throw new IllegalStateException("missing " + BASE);
            }
            try (Reader reader = new InputStreamReader(in, StandardCharsets.UTF_8)) {
                return withHook(JsonParser.parseReader(reader).getAsJsonObject());
            }
        } catch (IOException e) {
            throw new IllegalStateException("cannot read " + BASE, e);
        }
    }

    /** A copy of {@code base} (credit replaced, overrides dropped) with the hook elements appended. */
    public static JsonObject withHook(JsonObject base) {
        JsonObject model = base.deepCopy();
        model.addProperty("credit", "Generated by datagen from musket_loaded (GR3 placeholder until art/models/musket_hook.bbmodel)");
        model.remove("overrides");
        JsonArray elements = model.getAsJsonArray("elements");
        // in the barrel's own frame (before the -45 degree turn): x across, y along the barrel, z across
        double x = MUZZLE_X;
        double y = MUZZLE_Y;
        double z = MUZZLE_Z;
        elements.add(element(HOOK_ELEMENTS[0], x - 0.4, y - 1.0, z - 0.4, x + 0.4, y + 3.0, z + 0.4));
        elements.add(element(HOOK_ELEMENTS[1], x - 1.8, y + 2.6, z - 0.5, x + 1.8, y + 3.4, z + 0.5));
        elements.add(element(HOOK_ELEMENTS[2], x - 1.8, y + 1.4, z - 0.4, x - 1.0, y + 3.0, z + 0.4));
        elements.add(element(HOOK_ELEMENTS[3], x + 1.0, y + 1.4, z - 0.4, x + 1.8, y + 3.0, z + 0.4));
        return model;
    }

    private static JsonElement element(String name, double x0, double y0, double z0, double x1, double y1, double z1) {
        JsonObject e = new JsonObject();
        e.addProperty("name", name);
        e.add("from", vec(x0, y0, z0));
        e.add("to", vec(x1, y1, z1));
        JsonObject rotation = new JsonObject();
        rotation.addProperty("angle", BARREL_ANGLE);
        rotation.addProperty("axis", "z");
        rotation.add("origin", vec(MUZZLE_X, MUZZLE_Y, MUZZLE_Z));
        e.add("rotation", rotation);
        JsonObject faces = new JsonObject();
        for (String side : new String[]{"north", "east", "south", "west", "up", "down"}) {
            JsonObject face = new JsonObject();
            JsonArray uv = new JsonArray();
            // the iron of the hook item's shank on the palette
            uv.add(8.5);
            uv.add(0.5);
            uv.add(11.5);
            uv.add(3.5);
            face.add("uv", uv);
            face.addProperty("texture", "#0");
            faces.add(side, face);
        }
        e.add("faces", faces);
        return e;
    }

    private static JsonArray vec(double x, double y, double z) {
        JsonArray a = new JsonArray();
        a.add(round(x));
        a.add(round(y));
        a.add(round(z));
        return a;
    }

    private static double round(double v) {
        return Math.round(v * 1000.0) / 1000.0;
    }
}
