package com.richardsenger.piratesnships.core.client.gui;

import com.richardsenger.piratesnships.Constants;
import net.minecraft.resources.ResourceLocation;

import java.util.List;

/**
 * Ids of the GUI texture kit (work package U1) in vanilla's GUI sprite atlas: {@code pirates_n_ships:<path>} is
 * {@code assets/pirates_n_ships/textures/gui/sprites/<path>.png} plus its {@code .png.mcmeta} (nine-slice or stretch
 * scaling). All of them are generated by {@code tools/gen_gui_textures.py}; {@code GuiTexturesTest} checks that every
 * id here has both files and that the script's output matches the committed files. No client classes, so tests can
 * load it.
 */
public final class GuiSprites {

    // panels (nine-slice)
    public static final ResourceLocation FRAME = id("panel/frame");
    public static final ResourceLocation HEADER = id("panel/header");
    public static final ResourceLocation PARCHMENT = id("panel/parchment");
    public static final ResourceLocation CARD = id("panel/card");
    public static final ResourceLocation CARD_HOVER = id("panel/card_hover");
    public static final ResourceLocation CARD_OWN = id("panel/card_own");

    // widgets (nine-slice)
    public static final ResourceLocation BUTTON = id("widget/button");
    public static final ResourceLocation BUTTON_HOVER = id("widget/button_hover");
    public static final ResourceLocation BUTTON_PRESSED = id("widget/button_pressed");
    public static final ResourceLocation BUTTON_DISABLED = id("widget/button_disabled");
    public static final ResourceLocation FIELD = id("widget/field");
    public static final ResourceLocation FIELD_FOCUSED = id("widget/field_focused");
    public static final ResourceLocation TAG = id("widget/tag");
    public static final ResourceLocation TAG_HOVER = id("widget/tag_hover");
    public static final ResourceLocation DIVIDER = id("widget/divider");
    public static final ResourceLocation DIVIDER_VERTICAL = id("widget/divider_vertical");
    public static final ResourceLocation SCROLL_TRACK = id("widget/scroll_track");
    public static final ResourceLocation SCROLL_KNOB = id("widget/scroll_knob");
    public static final ResourceLocation SCROLL_KNOB_HOVER = id("widget/scroll_knob_hover");

    // icons (stretch, drawn at their pixel size)
    public static final ResourceLocation COIN = id("icon/coin");
    public static final ResourceLocation COIN_STACK = id("icon/coin_stack");
    public static final ResourceLocation WAX_SEAL = id("icon/wax_seal");
    public static final ResourceLocation NAVY_ANCHOR = id("icon/navy_anchor");
    public static final ResourceLocation PIN = id("icon/pin");
    /** Size of the 9x9 icons. */
    public static final int ICON = 9;

    // stamina bar
    public static final ResourceLocation STAMINA_TROUGH = id("hud/stamina_trough");
    public static final ResourceLocation STAMINA_TROUGH_ALERT = id("hud/stamina_trough_alert");
    /** 80x5, deep red (left) to amber (right). */
    public static final ResourceLocation STAMINA_FILL = id("hud/stamina_fill");
    /** 5x20, deep red (bottom) to amber (top). */
    public static final ResourceLocation STAMINA_FILL_VERTICAL = id("hud/stamina_fill_vertical");
    public static final ResourceLocation RIPOSTE = id("hud/riposte");
    public static final ResourceLocation LOCKOUT = id("hud/lockout");

    public static final List<ResourceLocation> ALL = List.of(
            FRAME, HEADER, PARCHMENT, CARD, CARD_HOVER, CARD_OWN,
            BUTTON, BUTTON_HOVER, BUTTON_PRESSED, BUTTON_DISABLED, FIELD, FIELD_FOCUSED, TAG, TAG_HOVER,
            DIVIDER, DIVIDER_VERTICAL, SCROLL_TRACK, SCROLL_KNOB, SCROLL_KNOB_HOVER,
            COIN, COIN_STACK, WAX_SEAL, NAVY_ANCHOR, PIN,
            STAMINA_TROUGH, STAMINA_TROUGH_ALERT, STAMINA_FILL, STAMINA_FILL_VERTICAL, RIPOSTE, LOCKOUT);

    private GuiSprites() {
    }

    private static ResourceLocation id(String path) {
        return Constants.id(path);
    }
}
