package com.richardsenger.piratesnships.ship.sable;

import com.richardsenger.piratesnships.Constants;
import com.richardsenger.piratesnships.platform.Services;
import com.richardsenger.piratesnships.platform.registry.RegistryEntry;
import dev.ryanhcode.sable.api.physics.force.ForceGroup;
import dev.ryanhcode.sable.api.physics.force.ForceGroups;
import net.minecraft.network.chat.Component;
import org.jetbrains.annotations.Nullable;

/**
 * Our Sable force groups ({@code api/physics/force/ForceGroup.java} l.15, registry {@code ForceGroups.REGISTRY_KEY},
 * {@code api/physics/force/ForceGroups.java}). A group is the bucket Sable sums point forces into and shows in its force
 * display; {@code ServerSubLevel#getOrCreateQueuedForceGroup} (l.395) creates the per-body accumulator on first use.
 */
public final class ShipForces {

    /** Translation key of the buoyancy group's name (generated by the hull module's lang provider). */
    public static final String BUOYANCY_KEY = "force_group." + Constants.MOD_ID + ".hull_buoyancy";

    /** Translation key of the sailing group's name (sails and keel, generated by the sailing module's lang provider). */
    public static final String SAILING_KEY = "force_group." + Constants.MOD_ID + ".sailing";

    /** Translation key of the grappling rope group's name (generated by the grapple module's lang provider). */
    public static final String GRAPPLE_KEY = "force_group." + Constants.MOD_ID + ".grapple";

    /** Translation key of the sea hazards group's name (generated by the hazards module's lang provider). */
    public static final String HAZARDS_KEY = "force_group." + Constants.MOD_ID + ".sea_hazards";

    /** Translation key of the cargo group's name (vanilla containers' weight, CW1, generated by the trade module's lang provider). */
    public static final String CARGO_KEY = "force_group." + Constants.MOD_ID + ".cargo";

    /** Translation key of the waves group's name (roll and pitch of the sea, WV1, generated by the hazards module's lang provider). */
    public static final String WAVES_KEY = "force_group." + Constants.MOD_ID + ".waves";

    private static @Nullable RegistryEntry<ForceGroup, ForceGroup> waves;
    private static @Nullable RegistryEntry<ForceGroup, ForceGroup> cargo;
    private static @Nullable RegistryEntry<ForceGroup, ForceGroup> hazards;
    private static @Nullable RegistryEntry<ForceGroup, ForceGroup> buoyancy;
    private static @Nullable RegistryEntry<ForceGroup, ForceGroup> grapple;
    private static @Nullable RegistryEntry<ForceGroup, ForceGroup> sailing;

    /** Translation key of the rope hauling group's name (GR5, generated by the grapple module's lang provider). */
    public static final String HAUL_KEY = "force_group." + Constants.MOD_ID + ".haul";

    private static @Nullable RegistryEntry<ForceGroup, ForceGroup> haul;

    /** Registers the rope hauling group (GR5: a player hauling a hooked ship by hand). Call from the grapple module's {@code registerContent()}. */
    public static void registerHaul() {
        if (haul == null) {
            haul = Services.REGISTRY.register(ForceGroups.REGISTRY_KEY, "haul",
                    () -> new ForceGroup(Component.translatable(HAUL_KEY), null, 0xc49a5a, true));
        }
    }

    /** The rope hauling force group, or null before {@link #registerHaul()} ran. */
    static @Nullable ForceGroup haul() {
        return haul != null ? haul.get() : null;
    }

    private ShipForces() {
    }

    /** Registers our groups into Sable's registry. Call from a module's {@code registerContent()}. */
    public static void register() {
        if (buoyancy == null) {
            buoyancy = Services.REGISTRY.register(ForceGroups.REGISTRY_KEY, "hull_buoyancy",
                    () -> new ForceGroup(Component.translatable(BUOYANCY_KEY), null, 0x3a7bd5, true));
        }
        if (sailing == null) {
            sailing = Services.REGISTRY.register(ForceGroups.REGISTRY_KEY, "sailing",
                    () -> new ForceGroup(Component.translatable(SAILING_KEY), null, 0xe0d8b0, true));
        }
    }

    /** Registers the grappling rope group (G11). Call from the grapple module's {@code registerContent()}. */
    public static void registerGrapple() {
        if (grapple == null) {
            grapple = Services.REGISTRY.register(ForceGroups.REGISTRY_KEY, "grapple",
                    () -> new ForceGroup(Component.translatable(GRAPPLE_KEY), null, 0x8b5a2b, true));
        }
    }

    /** Registers the sea hazards group (H1: waterspouts, whirlpools). Call from the hazards module's {@code registerContent()}. */
    public static void registerHazards() {
        if (hazards == null) {
            hazards = Services.REGISTRY.register(ForceGroups.REGISTRY_KEY, "sea_hazards",
                    () -> new ForceGroup(Component.translatable(HAZARDS_KEY), null, 0x2e8b8b, true));
        }
    }

    /** Registers the cargo group (CW1: the weight of vanilla containers). Call from the trade module's {@code registerContent()}. */
    public static void registerCargo() {
        if (cargo == null) {
            cargo = Services.REGISTRY.register(ForceGroups.REGISTRY_KEY, "cargo",
                    () -> new ForceGroup(Component.translatable(CARGO_KEY), null, 0x9c6b30, true));
        }
    }

    /** Registers the waves group (WV1: roll and pitch torque of the sea). Call from the hazards module's {@code registerContent()}. */
    public static void registerWaves() {
        if (waves == null) {
            waves = Services.REGISTRY.register(ForceGroups.REGISTRY_KEY, "waves",
                    () -> new ForceGroup(Component.translatable(WAVES_KEY), null, 0x4fa3d1, true));
        }
    }

    /** The waves force group, or null before {@link #registerWaves()} ran. */
    static @Nullable ForceGroup waves() {
        return waves != null ? waves.get() : null;
    }

    /** The cargo force group, or null before {@link #registerCargo()} ran. */
    static @Nullable ForceGroup cargo() {
        return cargo != null ? cargo.get() : null;
    }

    /** The sea hazards force group, or null before {@link #registerHazards()} ran. */
    static @Nullable ForceGroup hazards() {
        return hazards != null ? hazards.get() : null;
    }

    /** The grappling rope force group, or null before {@link #registerGrapple()} ran. */
    static @Nullable ForceGroup grapple() {
        return grapple != null ? grapple.get() : null;
    }

    /** The sail and keel force group, or null before {@link #register()} ran. */
    static @Nullable ForceGroup sailing() {
        return sailing != null ? sailing.get() : null;
    }

    /** The dry-volume and flood-water force group, or null before {@link #register()} ran. */
    static @Nullable ForceGroup buoyancy() {
        return buoyancy != null ? buoyancy.get() : null;
    }
}
