package com.richardsenger.piratesnships.trade.good;

import com.richardsenger.piratesnships.Constants;
import com.richardsenger.piratesnships.core.data.DefinitionType;
import com.richardsenger.piratesnships.trade.market.Climate;
import net.minecraft.resources.ResourceLocation;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static com.richardsenger.piratesnships.trade.market.Climate.ARID;
import static com.richardsenger.piratesnships.trade.market.Climate.COLD;
import static com.richardsenger.piratesnships.trade.market.Climate.TEMPERATE;
import static com.richardsenger.piratesnships.trade.market.Climate.TROPICAL;

/**
 * The {@code trade_good} definition type and the default goods generated by datagen. Pure logic takes a
 * {@code Definitions<TradeGood>} as a parameter and never reads {@link #TYPE}'s stores itself.
 *
 * <p>Weights use the provisions unit (one food item = 0.25). Prices are doubloons per unit at a neutral port.
 */
public final class TradeGoods {

    public static final DefinitionType<TradeGood> TYPE = DefinitionType.createSynced("trade_good", TradeGood.CODEC);

    public static final ResourceLocation SUGAR = Constants.id("sugar");
    public static final ResourceLocation FISH = Constants.id("fish");
    public static final ResourceLocation TIMBER = Constants.id("timber");
    public static final ResourceLocation IRON = Constants.id("iron");
    public static final ResourceLocation GRAIN = Constants.id("grain");
    public static final ResourceLocation HIDES = Constants.id("hides");
    public static final ResourceLocation COCOA = Constants.id("cocoa");
    public static final ResourceLocation GUNPOWDER = Constants.id("gunpowder");
    public static final ResourceLocation TOBACCO = Constants.id("tobacco");
    public static final ResourceLocation SPICES = Constants.id("spices");
    public static final ResourceLocation CLOTH = Constants.id("cloth");
    public static final ResourceLocation RUM = Constants.id("rum");

    /** The default set, in a fixed order. */
    public static final Map<ResourceLocation, TradeGood> DEFAULTS;

    static {
        Map<ResourceLocation, TradeGood> m = new LinkedHashMap<>();
        m.put(SUGAR, good("minecraft:sugar", 2.0, 0.25, GoodCategory.CROP, 1.0, 1.0, TROPICAL));
        m.put(FISH, good("minecraft:cod", 1.5, 0.25, GoodCategory.FOOD, 1.0, 1.5, TEMPERATE, COLD));
        m.put(TIMBER, good("minecraft:oak_log", 1.0, 1.0, GoodCategory.RAW_MATERIAL, 0.5, 2.0, TEMPERATE, COLD));
        m.put(IRON, good("minecraft:iron_ingot", 6.0, 1.0, GoodCategory.METAL, 0.8, 0.75, COLD, ARID));
        m.put(GRAIN, good("minecraft:wheat", 1.0, 0.25, GoodCategory.FOOD, 0.8, 1.5, TEMPERATE));
        m.put(HIDES, good("minecraft:leather", 3.0, 0.5, GoodCategory.RAW_MATERIAL, 1.0, 1.0, ARID, TEMPERATE));
        m.put(COCOA, good("minecraft:cocoa_beans", 4.0, 0.25, GoodCategory.CROP, 1.2, 0.75, TROPICAL));
        m.put(GUNPOWDER, good("minecraft:gunpowder", 8.0, 0.25, GoodCategory.MANUFACTURED, 1.2, 0.5));
        m.put(TOBACCO, good("pirates_n_ships:tobacco", 5.0, 0.25, GoodCategory.CROP, 1.2, 0.75, TROPICAL, ARID));
        m.put(SPICES, good("pirates_n_ships:spices", 12.0, 0.1, GoodCategory.LUXURY, 1.5, 0.5, TROPICAL));
        m.put(CLOTH, good("pirates_n_ships:cloth", 6.0, 0.5, GoodCategory.MANUFACTURED, 1.0, 0.75, TEMPERATE));
        // Same weight as rum in crew.provisions, so a bottle weighs the same in the hold and in the pantry
        m.put(RUM, good("pirates_n_ships:rum", 4.0, 0.5, GoodCategory.MANUFACTURED, 1.0, 1.0, TROPICAL));
        DEFAULTS = java.util.Collections.unmodifiableMap(m);
    }

    private TradeGoods() {
    }

    /** Loads the class so {@link #TYPE} is declared in time. Called from {@code registerContent()}. */
    public static void init() {
    }

    private static TradeGood good(String item, double price, double weight, GoodCategory category,
                                  double sensitivity, double stockFactor, Climate... producedIn) {
        return new TradeGood(ResourceLocation.parse(item), price, weight, category, sensitivity, stockFactor, List.of(producedIn));
    }
}
