package com.richardsenger.piratesnships.guide;

import com.google.gson.JsonObject;
import com.mojang.serialization.JsonOps;
import com.richardsenger.piratesnships.Constants;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.component.DataComponentType;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.ItemStack;

import java.util.Optional;

/**
 * The guide book: GuideME's generic guide item ({@code guideme:guide}) carrying our guide id in GuideME's data
 * component {@code guideme:guide_id} (refs/guideme src/main/java/guideme/internal/GuideME.java:32 and :51). GuideME is
 * an optional dependency and nothing here imports it: the item and the component are looked up by id, and the stack
 * is decoded with vanilla's {@link ItemStack#CODEC} from the same JSON the recipe result uses. The guide itself is
 * pure resources, generated by {@code tools/gen_guideme.py} from docs/guide.md.
 */
public final class GuideBook {

    /** Our guide: {@code assets/pirates_n_ships/guideme_guides/guide.json}, pages under {@code guides/pirates_n_ships/guide/}. */
    public static final ResourceLocation GUIDE_ID = Constants.id("guide");
    /** GuideME's mod id. */
    public static final String GUIDEME = "guideme";
    /** GuideME's generic guide item. */
    public static final ResourceLocation ITEM_ID = ResourceLocation.fromNamespaceAndPath(GUIDEME, "guide");
    /** GuideME's data component holding the guide id. */
    public static final ResourceLocation COMPONENT_ID = ResourceLocation.fromNamespaceAndPath(GUIDEME, "guide_id");

    /** Lang keys of the book's name and tooltip, referenced by the guide definition that gen_guideme.py writes. */
    public static final String NAME_KEY = "guide.pirates_n_ships.guide.name";
    public static final String TOOLTIP_KEY = "guide.pirates_n_ships.guide.tooltip";

    private GuideBook() {
    }

    /** The item stack JSON of one guide book: {@code {"count": 1, "components": {...}, "id": "guideme:guide"}}. */
    public static JsonObject stackJson() {
        JsonObject components = new JsonObject();
        components.addProperty(COMPONENT_ID.toString(), GUIDE_ID.toString());
        JsonObject json = new JsonObject();
        json.addProperty("count", 1);
        json.add("components", components);
        json.addProperty("id", ITEM_ID.toString());
        return json;
    }

    /** Whether GuideME's guide item and component are registered (GuideME is installed). */
    public static boolean available() {
        return BuiltInRegistries.ITEM.containsKey(ITEM_ID) && BuiltInRegistries.DATA_COMPONENT_TYPE.containsKey(COMPONENT_ID);
    }

    /** A new guide book, or empty when GuideME is not installed. */
    public static Optional<ItemStack> create(HolderLookup.Provider registries) {
        if (!available()) return Optional.empty();
        return ItemStack.CODEC.parse(registries.createSerializationContext(JsonOps.INSTANCE), stackJson())
                .resultOrPartial(error -> Constants.LOG.warn("Could not create the guide book: {}", error));
    }

    /** Whether {@code stack} is a guide book for our guide. */
    public static boolean isGuideBook(ItemStack stack) {
        if (stack.isEmpty() || !BuiltInRegistries.ITEM.getKey(stack.getItem()).equals(ITEM_ID)) return false;
        DataComponentType<?> type = BuiltInRegistries.DATA_COMPONENT_TYPE.get(COMPONENT_ID);
        return type != null && GUIDE_ID.equals(stack.get(type));
    }
}
