package com.richardsenger.piratesnships.core.gametest;

import com.richardsenger.piratesnships.Constants;

import java.util.List;

/**
 * Shared empty structure templates for GameTests, generated by datagen into {@code data/pirates_n_ships/structure}.
 * Tests build what they need themselves, so most tests never need their own template. If you need a bigger box,
 * add a constant and an entry to {@link #ALL} and rerun {@code runData}.
 */
public final class GameTestTemplates {

    /** A template id and its size in blocks. */
    public record Template(String id, int x, int y, int z) { }

    /** 3×3×3 of air. */
    public static final String EMPTY_3 = Constants.MOD_ID + ":empty_3x3x3";
    /** 9×6×9 of air, enough for a small hull. */
    public static final String EMPTY_9 = Constants.MOD_ID + ":empty_9x6x9";
    /** 24×12×24 of air, for ship-scale tests. */
    public static final String EMPTY_24 = Constants.MOD_ID + ":empty_24x12x24";

    /** 40×12×40 of air, for ships that move (sailing tests). */
    public static final String EMPTY_40 = Constants.MOD_ID + ":empty_40x12x40";

    /** 48×16×48 of air, for world structures (the seafarer village's dock head, pier and a street). */
    public static final String EMPTY_48 = Constants.MOD_ID + ":empty_48x16x48";

    /** 160×40×160 of air, for a ship's turning circle in deep water (SH2: the starter sloop turns about 100 blocks across). */
    public static final String EMPTY_160_DEEP = Constants.MOD_ID + ":empty_160x40x160";

    public static final List<Template> ALL = List.of(
            new Template(EMPTY_3, 3, 3, 3),
            new Template(EMPTY_9, 9, 6, 9),
            new Template(EMPTY_24, 24, 12, 24),
            new Template(EMPTY_40, 40, 12, 40),
            new Template(EMPTY_48, 48, 16, 48),
            new Template(EMPTY_160_DEEP, 160, 40, 160));

    private GameTestTemplates() {
    }
}
